### ISSUE TITLE
Nullpointer Exception when running Sift bench on JDK 21.0.2

### ISSUE THREAD

**Issue by HanSolo** [jbellis/jvector#194]
Cloned the repository and have build jvector with Azul Zulu 21.0.2
When I run ```./mvnw compile exec:exec@sift``` on Zulu 21.0.2, it will crash after a couple of seconds with a NullPointer Exception. This also happens when I try to run it on Zulu 11.0.22 using ```./mvn -Pjdk11 compile exec:exec@sift```
Please find more information about the used machine, java version and the complete command line output in the attached crash.txt file.
Is there anything missing when running the sift test?

[crash.txt](https://github.com/jbellis/jvector/files/14083732/crash.txt)

**Comment by jbellis** [comment]
Thanks for the bug report -- fixed in abee1702e9404ef8fbca5e73027553694700b31e.

**Comment by rd-99** [comment]
@jbellis let me know if a new issue is required for this.
Currently i am still receiving NullPointer Exception (ravv= Null).
Coincidently variable which causes this error is unused. Removing it removes the error.
![error](https://github.com/jbellis/jvector/assets/63721098/62bdf810-0f9c-4d25-a7de-c0567c76632c)

`var dimension = ravv.dimension();`
Dimension is unused

**Comment by jbellis** [comment]
Thanks.  No, we don't need a new issue.

I pushed a fix for this, but I also reverted the path change -- siftsmall/ is the correct relative path when running `./mvnw compile exec:exec@sift` on openjdk + linux.  Not sure why it's different for you or how to make it generalize correctly.
